"""initial_schema

Revision ID: 5720e6e42c6a
Revises: 
Create Date: 2026-02-28 11:54:44.735868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5720e6e42c6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('delivery_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('payment_speed_rating', sa.Float(), nullable=False),
    sa.Column('purchase_history_count', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('idx_buyers_delivery_location', 'buyers', ['delivery_location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('farmers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('farm_name', sa.String(length=300), nullable=True),
    sa.Column('farm_size_hectares', sa.Float(), nullable=True),
    sa.Column('quality_rating', sa.Float(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('idx_farmers_location', 'farmers', ['location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('middlemen',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('current_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('truck_capacity_kg', sa.Float(), nullable=False),
    sa.Column('truck_plate', sa.String(length=20), nullable=False),
    sa.Column('route_radius_km', sa.Float(), nullable=False),
    sa.Column('on_time_rating', sa.Float(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('truck_plate')
    )
    op.create_index('idx_middlemen_current_location', 'middlemen', ['current_location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=False),
    sa.Column('available_volume_kg', sa.Float(), nullable=False),
    sa.Column('unit_price_asking', sa.Float(), nullable=False),
    sa.Column('accepted_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('LISTED', 'NEGOTIATING', 'LOGISTICS_SEARCH', 'IN_TRANSIT', 'SETTLED', 'CANCELLED', name='order_status_enum'), nullable=False),
    sa.Column('route_vector', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('crop_image_url', sa.String(length=500), nullable=True),
    sa.Column('quality_grade', sa.String(length=10), nullable=True),
    sa.Column('logistics_search_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_qr_hash', sa.String(length=64), nullable=True),
    sa.Column('delivery_qr_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_route_vector', 'orders', ['route_vector'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False, if_not_exists=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_order_id'), 'audit_logs', ['order_id'], unique=False, if_not_exists=True)
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('offered_price_per_kg', sa.Float(), nullable=False),
    sa.Column('volume_kg', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='bid_status_enum'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_order_id'), 'bids', ['order_id'], unique=False, if_not_exists=True)
    op.create_table('escrows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('total_amount_cents', sa.Integer(), nullable=False),
    sa.Column('farmer_released_cents', sa.Integer(), nullable=False),
    sa.Column('middleman_released_cents', sa.Integer(), nullable=False),
    sa.Column('refunded_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_FUNDS', 'FUNDS_HELD', 'PICKED_UP', 'DELIVERED', 'CANCELLED', name='escrow_status_enum'), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_transfer_farmer_pickup_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_transfer_farmer_final_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_transfer_middleman_id', sa.String(length=100), nullable=True),
    sa.Column('funds_held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('logistics_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('middleman_id', sa.UUID(), nullable=False),
    sa.Column('pickup_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('dropoff_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('agreed_fee_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OFFERED', 'ACCEPTED', 'REJECTED', name='assignment_status_enum'), nullable=False),
    sa.Column('last_gps_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('estimated_distance_km', sa.Float(), nullable=True),
    sa.Column('offered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['middleman_id'], ['middlemen.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_logistics_assignments_dropoff_location', 'logistics_assignments', ['dropoff_location'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('idx_logistics_assignments_pickup_location', 'logistics_assignments', ['pickup_location'], unique=False, postgresql_using='gist', if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_logistics_assignments_pickup_location', table_name='logistics_assignments', postgresql_using='gist')
    op.drop_index('idx_logistics_assignments_dropoff_location', table_name='logistics_assignments', postgresql_using='gist')
    op.drop_table('logistics_assignments')
    op.drop_table('escrows')
    op.drop_index(op.f('ix_bids_order_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_audit_logs_order_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('idx_orders_route_vector', table_name='orders', postgresql_using='gist')
    op.drop_table('orders')
    op.drop_index('idx_middlemen_current_location', table_name='middlemen', postgresql_using='gist')
    op.drop_table('middlemen')
    op.drop_index('idx_farmers_location', table_name='farmers', postgresql_using='gist')
    op.drop_table('farmers')
    op.drop_index('idx_buyers_delivery_location', table_name='buyers', postgresql_using='gist')
    op.drop_table('buyers')
    # ### end Alembic commands ###
